version: '3'
services:
  dnsninja-backend:
    build: ./backend
    container_name: dnsninja-backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - dnsninja

  dnsninja-frontend:
    build: ./frontend
    container_name: dnsninja-frontend
    ports:
      - "80:3000"
    restart: always
    environment:
      - DNS_NINJA_API=dnsninja-backend:8080
    networks:
      - dnsninja

networks:
  dnsninja: